#----------------------------------------------------------------------------
# Makefile for GNU make
#----------------------------------------------------------------------------


#------ Compiler and tools

CC       = gcc
# Using gcc instead of ld because it's broken on Ubuntu.
LINK     = gcc
LDCONFIG = /sbin/ldconfig
INSTALL  = install


#------ Target settings

VER_M        = 0
VER_MM       = 0.3
GLV_SO       = libglv-vk.so
GLV_TARGET   = $(GLV_SO).$(VER_MM)
#GLV_CFLAGS   = -fPIC -Wall -W -Wno-unused-parameter -O3 -DNDEBUG
GLV_CFLAGS   = -fPIC -Wall -W -Wno-unused-parameter -g -DDEBUG
GLV_INCPATH  = -I.
GLV_LFLAGS   = -shared
GLV_LIBS     =
GLV_OBJECTS  = glv.o
PREFIX       = /usr/local
# DESTDIR used for staged installs.
LIB_DIR      = $(DESTDIR)$(PREFIX)/lib
HEADER_DIR   = $(DESTDIR)$(PREFIX)/include/GL


GLV_CFLAGS  += -DVK_USE_PLATFORM_XLIB_KHR
ifdef VULKAN_SDK
GLV_CFLAGS  += -I$(VULKAN_SDK)/include
endif
GLV_CFLAGS  += -DUSE_XF86VMODE
GLV_LIBS    += -lXxf86vm
# GLV_LIBS    += -L/usr/X11R6/lib
# GLV_LIBS    += -L/usr/X11R6/lib64

# GLV_CFLAGS += -DUSE_XME
# GLV_LIBS   += -L/usr/X11R6/lib -lXxme

GLV_LIBS    += -lXext -lX11


#------ Build rules

all: $(GLV_TARGET)
 
$(GLV_TARGET): $(GLV_OBJECTS)
	$(LINK) -o $@ -Wl,-soname,$(GLV_SO).$(VER_M) $(GLV_LFLAGS) $(GLV_OBJECTS) $(GLV_LIBS)
	ln -sf $(GLV_TARGET) $(GLV_SO).$(VER_M)
	ln -sf $(GLV_TARGET) $(GLV_SO)
 
.PHONY: clean
clean:
	-rm -f $(GLV_TARGET) $(GLV_OBJECTS)

.PHONY: install
install:
	mkdir -p $(HEADER_DIR)
	mkdir -p $(LIB_DIR)
	$(INSTALL) -m 644 glv.h glv_keys.h $(HEADER_DIR)
	$(INSTALL) -m 755 $(GLV_TARGET) $(LIB_DIR)
	ln -sf $(GLV_TARGET) $(LIB_DIR)/$(GLV_SO).$(VER_M)
	ln -sf $(GLV_TARGET) $(LIB_DIR)/$(GLV_SO)
	$(LDCONFIG) -v -n $(LIB_DIR)

.PHONY: uninstall
uninstall:
	-rm -f $(LIB_DIR)/$(GLV_SO)
	-rm -f $(LIB_DIR)/$(GLV_SO).$(VER_M)
	-rm -f $(LIB_DIR)/$(GLV_SO).$(VER_MM)
	-rm -f $(HEADER_DIR)/glv.h $(HEADER_DIR)/glv_keys.h


#------ Compile rules

glv.o: glv.c glv.h
	$(CC) -c $(GLV_CFLAGS) -o glv.o $(GLV_INCPATH) glv.c


#EOF
