

struct KeyStr
{
    int code;
    char* str;
};


struct KeyStr keyStrings[] =
{
    { KEY_Grave,       "KEY_Grave" },
    { KEY_Escape,      "KEY_Escape" },
    { KEY_Space,       "KEY_Space" },
    { KEY_Return,      "KEY_Return" },
    { KEY_Tab,         "KEY_Tab" },
    { KEY_Back_Space,  "KEY_Back_Space" },
    { KEY_Print,       "KEY_Print" },
    { KEY_Scroll_Lock, "KEY_Scroll_Lock" },
    { KEY_Pause,       "KEY_Pause" },
    { KEY_Num_Lock,    "KEY_Num_Lock" },
    { KEY_Bracket_L,   "KEY_Bracket_L" },
    { KEY_Bracket_R,   "KEY_Bracket_R" },
    { KEY_Minus,       "KEY_Minus" },
    { KEY_Equal,       "KEY_Equal" },
    { KEY_Backslash,   "KEY_Backslash" },
    { KEY_Semicolon,   "KEY_Semicolon" },
    { KEY_Apostrophe,  "KEY_Apostrophe" },
    { KEY_Comma,       "KEY_Comma" },
    { KEY_Period,      "KEY_Period" },
    { KEY_Slash,       "KEY_Slash" },
    { KEY_Left,        "KEY_Left" },
    { KEY_Right,       "KEY_Right" },
    { KEY_Up,          "KEY_Up" },
    { KEY_Down,        "KEY_Down" },
    { KEY_Insert,      "KEY_Insert" },
    { KEY_Delete,      "KEY_Delete" },
    { KEY_Home,        "KEY_Home" },
    { KEY_End,         "KEY_End" },
    { KEY_Page_Up,     "KEY_Page_Up" },
    { KEY_Page_Down,   "KEY_Page_Down" },

    { KEY_KP_Up,       "KEY_KP_Up" },
    { KEY_KP_Begin,    "KEY_KP_Begin" },
    { KEY_KP_Left,     "KEY_KP_Left" },
    { KEY_KP_Right,    "KEY_KP_Right" },
    { KEY_KP_Home,     "KEY_KP_Home" },
    { KEY_KP_Down,     "KEY_KP_Down" },
    { KEY_KP_Page_Up,  "KEY_KP_Page_Up" },
    { KEY_KP_Page_Down,"KEY_KP_Page_Down" },
    { KEY_KP_End,      "KEY_KP_End" },
    { KEY_KP_Insert,   "KEY_KP_Insert" },
    { KEY_KP_Delete,   "KEY_KP_Delete" },
    { KEY_KP_Enter,    "KEY_KP_Enter" },
    { KEY_KP_Divide,   "KEY_KP_Divide" },
    { KEY_KP_Multiply, "KEY_KP_Multiply" },
    { KEY_KP_Add,      "KEY_KP_Add" },
    { KEY_KP_Separator,"KEY_KP_Separator" },
    { KEY_KP_Subtract, "KEY_KP_Subtract" },
    { KEY_KP_Decimal,  "KEY_KP_Decimal" },
    { KEY_KP_Equal,    "KEY_KP_Equal" },

    { KEY_Caps_Lock,   "KEY_Caps_Lock" },
    { KEY_Shift_L,     "KEY_Shift_L" },
    { KEY_Shift_R,     "KEY_Shift_R" },
    { KEY_Control_L,   "KEY_Control_L" },
    { KEY_Control_R,   "KEY_Control_R" },
    { KEY_Alt_L,       "KEY_Alt_L" },
    { KEY_Alt_R,       "KEY_Alt_R" },
    { KEY_Meta_L,      "KEY_Meta_L" },
    { KEY_Meta_R,      "KEY_Meta_R" },

    { KEY_1, "KEY_1" },
    { KEY_2, "KEY_2" },
    { KEY_3, "KEY_3" },
    { KEY_4, "KEY_4" },
    { KEY_5, "KEY_5" },
    { KEY_6, "KEY_6" },
    { KEY_7, "KEY_7" },
    { KEY_8, "KEY_8" },
    { KEY_9, "KEY_9" },
    { KEY_0, "KEY_0" },

    { KEY_a, "KEY_a" },
    { KEY_b, "KEY_b" },
    { KEY_c, "KEY_c" },
    { KEY_d, "KEY_d" },
    { KEY_e, "KEY_e" },
    { KEY_f, "KEY_f" },
    { KEY_g, "KEY_g" },
    { KEY_h, "KEY_h" },
    { KEY_i, "KEY_i" },
    { KEY_j, "KEY_j" },
    { KEY_k, "KEY_k" },
    { KEY_l, "KEY_l" },
    { KEY_m, "KEY_m" },
    { KEY_n, "KEY_n" },
    { KEY_o, "KEY_o" },
    { KEY_p, "KEY_p" },
    { KEY_q, "KEY_q" },
    { KEY_r, "KEY_r" },
    { KEY_s, "KEY_s" },
    { KEY_t, "KEY_t" },
    { KEY_u, "KEY_u" },
    { KEY_v, "KEY_v" },
    { KEY_w, "KEY_w" },
    { KEY_x, "KEY_x" },
    { KEY_y, "KEY_y" },
    { KEY_z, "KEY_z" },

    { KEY_F1, "KEY_F1" },
    { KEY_F2, "KEY_F2" },
    { KEY_F3, "KEY_F3" },
    { KEY_F4, "KEY_F4" },
    { KEY_F5, "KEY_F5" },
    { KEY_F6, "KEY_F6" },
    { KEY_F7, "KEY_F7" },
    { KEY_F8, "KEY_F8" },
    { KEY_F9, "KEY_F9" },
    { KEY_F10, "KEY_F10" },
    { KEY_F11, "KEY_F11" },
    { KEY_F12, "KEY_F12" },
    { KEY_F13, "KEY_F13" },
    { KEY_F14, "KEY_F14" },
    { KEY_F15, "KEY_F15" },

    { 0, 0 }
};


